[versions]
kotlin = "2.3.0"
kotlinx-datetime = "0.7.1"
kotest = "6.0.7"
kover = "0.9.4"
benchmark = "0.4.15"
compose = "1.9.3"
maven-publish = "0.35.0"

[libraries]
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-benchmark = { group = "org.jetbrains.kotlinx", name = "kotlinx-benchmark-runtime", version.ref = "benchmark" }
kotest-assetions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }


[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "benchmark" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }