[versions]
kotlin = "1.9.22"
kotlinx-datetime = "0.5.0"
kotest = "5.8.0"

[libraries]
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotest-assetions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }


[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }